### ISSUE TITLE
Can't write a PGM

### ISSUE THREAD

**Issue by AndoKarim** [eug/imageio-pnm#2]
Hello,
I don't understand a problem I have with the library. When i got a PGM image in enter and write a PGM everything work. But when i have in enter a PGM and I write a [PNG/BMP...] it doesn't create the image. And if I take a [PNG/JPG/BMP] and write a PGM it works. 
Is the problem because off we have a PGMBufferImage and not a simple BufferImage? 

Thank you and happy new year!

**Comment by eug** [comment]
First, sorry about the delay.

Second, the issue you have mentioned is because I haven't implemented the plugin to do this type of conversion (my bad). And even worst, I haven't documented this (sorry again).

Since I'm not using this library anymore, you can feel free to fork and implement such a feature. Also, if you are interested I can add you as a collab on this project.

**Comment by AndoKarim** [comment]
Haha no problem,

just to tell you that I edited your library to support this feature. If you
want to add me, I could add this ;)

Thank you

**Comment by eug** [comment]
Done! Before you merge, just let me review your code first by opening a PR.

Cheers!
